---
- name: To install Java on RedHat
  ansible.builtin.include_tasks: install-Redhat.yml
  when:
    ansible_os_family == 'RedHat'

- name: To install Java on Debian
  ansible.builtin.include_tasks: install-Debian.yml
  when:
    ansible_os_family == 'Debian'
