---
# Variable setup.

- name: Include file for remote system configuration
  include_tasks: pre_flight_check.yml

- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include admin variables
  include_vars:
    file: adminpass.yml
    
- include_tasks: install_java.yml

- name: Define jenkins_repo_url
  set_fact:
    jenkins_repo_url: "{{ jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  set_fact:
    jenkins_repo_key_url: "{{ jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  set_fact:
    jenkins_pkg_url: "{{ jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure Jenkins init settings.
- include_tasks: settings.yml

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Wait for Jenkins to start up before proceeding.
  command: "curl -sI http://localhost:8080/cli/"
  register: result
  retries: "{{ jenkins_connection_retries | default(30) }}"
  delay: "{{ jenkins_connection_delay | default(5) }}"
  until: result is defined and result.stdout is defined and
         (
           "'403 Forbidden' in result.stdout" or
           (
             "'200 OK' in result.stdout" and
             "'Please wait while' not in result.stdout"
           )
         )
  failed_when: false
  changed_when: false


- name: check if jenkins-cli jar file exists
  stat:
    path: "{{ jenkins_jar_location }}"
  register: Jenkins_jar_path

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: false
  when: not Jenkins_jar_path.stat.exists

- name: Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

# Update Jenkins and install configured plugins.
- include_tasks: plugins.yml

- name: Including file for managing configuration as code
  include_tasks: configuration_as_code_task.yml
  when: configuration_as_code == "enabled"
