# ---
# - name: Modify variables in init file
#   lineinfile:
#     dest: "{{ jenkins_init_file }}"
#     insertafter: '^{{ item.option }}='
#     regexp: '^{{ item.option }}=\"\${{ item.option }} '
#     line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
#     state: present
#   with_items:
#     - "{{ jenkins_init_changes }}"
#   register: jenkins_init_prefix
#   notify:
#     - Restart jenkins

# - name: Set the Jenkins home directory
#   lineinfile:
#     dest: "{{ jenkins_init_file }}"
#     regexp: '^JENKINS_HOME=.*'
#     line: 'JENKINS_HOME={{ jenkins_home }}'
#   register: jenkins_home_config

# - name: Set HTTP port in Jenkins config.
#   lineinfile:
#     backrefs: true
#     dest: "{{ jenkins_init_file }}"
#     regexp: '^{{ jenkins_http_port_param }}='
#     line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
#   register: jenkins_http_config

# - name: Ensure jenkins_home {{ jenkins_home }} exists
#   file:
#     path: "{{ jenkins_home }}"
#     state: directory
#     owner: jenkins
#     group: jenkins
#     mode: u+rwx
#     follow: true

# - name: Create custom init scripts directory.
#   file:
#     path: "{{ jenkins_home }}/init.groovy.d"
#     state: directory
#     owner: "{{ jenkins_process_user }}"
#     group: "{{ jenkins_process_group }}"
#     mode: 0775

# - name: Trigger handlers immediately in case Jenkins was installed
#   meta: flush_handlers

---

# === Handle classic init file (Ubuntu <=22.04) ===
- block:
    - name: Modify variables in init file
      lineinfile:
        dest: "{{ jenkins_init_file }}"
        insertafter: '^{{ item.option }}='
        regexp: '^{{ item.option }}=\"\${{ item.option }} '
        line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
        state: present
      loop: "{{ jenkins_init_changes }}"
      register: jenkins_init_prefix
      notify: Restart jenkins

    - name: Set the Jenkins home directory
      lineinfile:
        dest: "{{ jenkins_init_file }}"
        regexp: '^JENKINS_HOME=.*'
        line: 'JENKINS_HOME={{ jenkins_home }}'
      register: jenkins_home_config

    - name: Set HTTP port in Jenkins config.
      lineinfile:
        backrefs: true
        dest: "{{ jenkins_init_file }}"
        regexp: '^{{ jenkins_http_port_param }}='
        line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
      register: jenkins_http_config
  when: jenkins_init_file is file

# === Handle systemd (Ubuntu >=24.04) ===
- block:
    - name: Ensure Jenkins systemd override directory exists
      file:
        path: /etc/systemd/system/jenkins.service.d
        state: directory
        mode: '0755'

    - name: Configure Jenkins systemd override
      copy:
        dest: /etc/systemd/system/jenkins.service.d/override.conf
        content: |
          [Service]
          Environment="JAVA_ARGS=-Djenkins.install.runSetupWizard=false"
          Environment="JENKINS_ARGS=--prefix="
          Environment="JENKINS_HOME={{ jenkins_home }}"
          Environment="JENKINS_PORT={{ jenkins_http_port }}"
        mode: '0644'
      notify: Restart jenkins
  when: jenkins_init_file is not file

# === Common tasks ===
- name: Ensure jenkins_home {{ jenkins_home }} exists
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers

